"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.urls import reverse_lazy

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9v&*3_@_029tixk300k9uz75m#@p(6(w@&-gm-ed14v*@+5)z2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['xn--80aairftm.pp.ua', '127.0.0.1']
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    #'django.contrib.contenttypes.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop_app.apps.ShopAppConfig',
	'test_url.apps.TestUrlConfig',
    #'blog.apps.BlogConfig',
    'rest_framework',
    'dj_pagination',
    'api',
    'corsheaders',
    #Local
    'articles.apps.ArticlesConfig',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'accounts.apps.AccountsConfig',
    # 'CustomUser',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dj_pagination.middleware.PaginationMiddleware',
]

ROOT_URLCONF = 'shop.urls'
#big_retail/os.path.join(BASE_DIR, 'shop_app/templates/shop_app/big_retail'),
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'shop_app/templates/shop_app'),
                 os.path.join(BASE_DIR, 'shop_app/templates/')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.i18n',
                'shop_app.context_processors.gallery_index_tmp',
                'articles.context_processors.object_list',
                'shop_app.context_processors.media_url_cart'
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'shop_pos',
        'USER': 'shopuser',
        'PASSWORD': 'shop_pos0701',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, "bootstrap"),
    os.path.join(BASE_DIR, 'shop_app/static'),
    os.path.join(BASE_DIR, 'test_url/static'),
    os.path.join(BASE_DIR, 'shop_app/static/big_retail'),
]

STATICFILES_FINDERS = (

    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",

)
#https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SESSION_ENGINE
# SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
#https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/%D0%A1%D0%B5%D1%81%D1%81%D0%B8%D0%B8
SESSION_SAVE_EVERY_REQUEST = True


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False

CORS_ORIGIN_WHITELIST = [
    'http://google.com'
    'localhost:8800'
    'localhost:8005'
    '127.0.0.1'
    '127.0.0.1/api'
    'http://127.0.0.1'
    'http://127.0.0.1/api'
    'http://127.0.0.1/'
    'http://127.0.0.1/api'
    # 'http://localhost:8800'
    'http://127.0.0.1:8800'
    'http://127.0.0.1:8800/api'
    'http://127.0.0.1:8005'
    'http://xn--80aairftm.pp.ua:8005'
    'http://127.0.0.1:8005/api'
    'http://xn--80aairftm.pp.ua:8005/api'
    '127.0.0.1:8005'
    'xn--80aairftm.pp.ua:8005'
    '127.0.0.1:8005/api'
    'xn--80aairftm.pp.ua'
    'xn--80aairftm.pp.ua/api'
    'xn--80aairftm.pp.ua:8005/api'
    # 'https://www.youtube.com'
    # 'https://googleads.g.doubleclick.net'
    'gdata.youtube.com'
    'googleads.g.doubleclick.net'
    '*'

    # 'http://gdata.youtube.com/feeds/api/videos/8hv-ol3'
    # 'https://gdata.youtube.com/feeds/api/videos/8hv-ol3RnPo?v=2&alt=jsonc'
    # '*'
]

AUTHENTICATION_BACKENDS = (

    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_FORMS = {'signup': 'accounts.forms.SimpleSignupForm'}
AUTH_USER_MODEL = 'accounts.CustomUser'
# AUTH_USER_MODEL = 'auth.User'

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = False #'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.ukr.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL = 'tinez99@ukr.net'
EMAIL_HOST_PASSWORD = ''

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'
# LOGOUT_REDIRECT_URL = '/'
# LOGIN_URL = reverse_lazy('login')
# LOGOUT_URL = reverse_lazy('logout')
# AUTH_USER_MODEL = 'accounts.CustomUser'