# Generated by Django 2.2 on 2021-01-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210126_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lead',
            field=models.CharField(default=0, help_text='0 постоянный покупатель, 1 лид', max_length=12, verbose_name='Лид'),
        ),
    ]
