# Generated by Django 2.2 on 2020-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('goodsname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название')),
                ('catid', models.CharField(blank=True, max_length=15, verbose_name='id категории')),
                ('price', models.CharField(blank=True, max_length=30, verbose_name='Цена')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Основное изображение')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тоовар',
                'verbose_name_plural': 'Товары',
                'db_table': 'goods',
            },
        ),
    ]
