# Generated by Django 2.2 on 2021-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='null_one',
            field=models.IntegerField(default='0', verbose_name='Ноль или один'),
        ),
    ]
