# Generated by Django 2.2 on 2020-09-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='название')),
                ('sum', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'shop_billing',
            },
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='catname',
            field=models.CharField(blank=True, max_length=15, verbose_name='название'),
        ),
    ]
