# Generated by Django 2.2 on 2021-07-21 18:58

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20210721_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsmodel',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('price'), nulls_last=True)], 'verbose_name': 'Тоовар', 'verbose_name_plural': 'Товары'},
        ),
    ]
