# Generated by Django 2.2 on 2020-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20200917_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(blank=True, max_length=30, verbose_name='id покупки')),
                ('tovar_name', models.CharField(blank=True, max_length=30, verbose_name='название')),
                ('price', models.CharField(blank=True, max_length=30, verbose_name='Цена')),
                ('img', models.CharField(blank=True, max_length=30, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'shop_orders',
            },
        ),
        migrations.AlterModelOptions(
            name='billingmodel',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='sum',
            field=models.TextField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
