# Generated by Django 2.2 on 2020-09-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20200917_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingmodel',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
    ]
