# Generated by Django 2.2 on 2020-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='catid',
            field=models.IntegerField(blank=True, max_length=15, verbose_name='id категории'),
        ),
    ]
