# Generated by Django 2.2 on 2020-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20200924_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='catid',
            field=models.IntegerField(null=True, verbose_name='id категории'),
        ),
    ]
