# Generated by Django 2.2 on 2020-10-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop_app', '0008_auto_20200924_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
