# Generated by Django 2.2 on 2020-10-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop_app', '0009_auto_20201010_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
