# Generated by Django 2.2 on 2020-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20201010_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='catid',
            field=models.IntegerField(null=True, verbose_name='id категории'),
        ),
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='image',
            name='goodsname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Цена'),
        ),
    ]
