# Generated by Django 2.2 on 2020-10-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_auto_20201010_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='catid',
        ),
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='image',
            name='goodsname',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='price',
        ),
    ]
