# Generated by Django 2.2 on 2020-10-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20201022_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsmodel',
            old_name='catid',
            new_name='category',
        ),
    ]
