# Generated by Django 2.2 on 2020-12-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_auto_20201023_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='img',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фото'),
        ),
    ]
