# Generated by Django 2.2 on 2021-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_auto_20201220_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='cat_true',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='category',
            field=models.CharField(choices=[('1', 'Разное'), ('2', 'Одежда'), ('3', 'Аппаратура'), ('4', 'Книги')], max_length=15, null=True, verbose_name='Категории'),
        ),
    ]
