# Generated by Django 2.2 on 2021-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_auto_20210107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='cat_true',
            field=models.PositiveIntegerField(max_length=15, null=True),
        ),
    ]
