# Generated by Django 2.2 on 2021-01-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0020_auto_20210107_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(blank=True, default='0', verbose_name='Описание'),
        ),
    ]
