# Generated by Django 2.2 on 2021-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_auto_20210107_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='cat_true',
            field=models.PositiveIntegerField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='category',
            field=models.CharField(choices=[('1', 'Одежда'), ('2', 'Аппаратура'), ('3', 'Книги'), ('4', 'Разное')], max_length=15, null=True, verbose_name='Категории'),
        ),
    ]
