# Generated by Django 2.2 on 2021-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_auto_20210107_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='cat_true',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
